---
title: "Resistance databases"
params:
  resistance_summary:
  resistance_gff:
  is_CARD:
  card_summary:
  is_Resfinder:
---
```{r echo=FALSE}
library(magrittr)

resistance_summary <- params$resistance_summary
resistance_gff <- params$resistance_gff
is_CARD <- params$is_CARD
card_summary <- params$card_summary
is_Resfinder <- params$is_Resfinder
```

#### Resistance databases

In this pipeline, the resistance genes can be annotated from two different databases:

* Resfinder database and;
    * Was this database used? - ``r is_Resfinder``
* CARD database.
    * Was this database used? - ``r is_CARD``
* Files containg genes pottentially related to resistance:
    * GFF: ``r resistance_gff``
    * Summary table: ``r resistance_summary``

##### Summary table overview:

```{r echo=FALSE, comment="", eval=TRUE}
if (file.info(params$resistance_summary)$size > 0) {
df <- read.delim(params$resistance_summary, header = TRUE, sep = "\t")
df } else {cat("The summary table for this database is empty. Or the database was not used, or no element were found!")}
```

```{r, CARD_conditional_block, echo=FALSE, results='asis', eval=is_CARD, child='CARD.Rmd'}
```