
The following tables summarizes the results obtained with AMRFinderPlus. It can be divided into two main categories: Genes related to antibiotics (AMR) and those not related to it. This division is addressed in column one of Table \@ref(tab:ncbi-amr-resistance-genes).

Additionally, gene targets are summarised in image \@ref(fig:ncbi-resistome-png)

```{r results='asis'}
# Create Position Column
ncbi_amr$`Query Protein Coordinates` <- paste(ncbi_amr$seqname, ":", ncbi_amr$start, "-", ncbi_amr$end)

# Parse again
genes <- ncbi_amr %>% select(Prokka_ID, `Query Protein Coordinates`)

# To upper
genes$Prokka_ID <- toupper(ncbi_amr$Prokka_ID)

# Read result
tab <- amrtsv

# Create List
string.list <- tab %>% filter(Element.type == "AMR") %>% pull(2) %>% unique()
cat("- AMR genes found in the query genome:\n")
cat(paste("\t-", string.list), sep = '\n')
```

```{r ncbi-amr-resistance-genes}
# Merge tables
tab2 <- merge.data.frame(genes, tab, by.x = "Prokka_ID", by.y = "Protein.identifier")

# Create urls
urls <- lapply(tab2$Accession.of.closest.sequence, function(x){
  ifelse(!is.na(x), paste0("https://www.ncbi.nlm.nih.gov/gene/?term=", x),
         paste0("No Reference"))
  })

# Produce Table
tab2 %>%
  select(Element.type, Prokka_ID, Gene.symbol, Sequence.name, Class, Method, Accession.of.closest.sequence, `Query Protein Coordinates`) %>%
  mutate("Accession.of.closest.sequence" = ifelse(!is.na(Accession.of.closest.sequence), cell_spec(Accession.of.closest.sequence, "html", link = urls), NA)) %>%
  arrange(Element.type, Prokka_ID) %>%
kable(caption = "Resistance genes annotated from NCBI AMR curated database using AMRfinderplus", escape = FALSE, col.names = c("Resistance Type", "Query Protein ID", "Gene Name", "Product", "Target Drug Class", "Annotation Method", "Reference Sequence", "Genome Coordinates")) %>%
  kable_styling(bootstrap_options = bt_opt, full_width = T, fixed_thead = T, font_size = 12) %>%
  collapse_rows(columns = 1, valign = "middle")
```

```{r ncbi-resistome-png, fig.align='center', fig.show='hold', fig.cap="Resistome Predicted using NCBI's AMRFinderplus", out.width="60%"}
ncbi_count <- tab2 %>%
  select(3,7)
drugs <- plyr::count(ncbi_count, "Class")
ggplot(drugs, aes(x=Class, y=freq, fill=Class)) +
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  xlab("Gene Target") +
  ylab("Number of genes") +
  guides(fill=guide_legend(title = "Gene Target"))
```
